# frozen_string_literal: true

source "https://rubygems.org"

gem "rails", "~> 8.0"
gem "puma",  "~> 6.4"

gem "poli_page-rails", path: "../"
gem "poli-page",       path: "../../sdk-ruby"

gem "dotenv-rails", "~> 3.1"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[windows jruby]

group :development do
  gem "web-console"
end

group :development, :test do
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
end
